/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4OHEkrGppHE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function HeroSection() {
  return (
    <section className="flex flex-col items-center justify-center w-full min-h-screen bg-gradient-to-r from-purple-600 to-blue-500 text-white text-center p-8">
      <div className="flex flex-col items-center">
        <img src="/placeholder.svg" alt="MYHackathon Logo" className="mb-4 w-[300px] h-[100px]" />
        <h1 className="text-5xl font-bold mb-2">
          <span className="block">&lt;MYHACKATHON/&gt;</span>
        </h1>
        <h2 className="text-2xl font-semibold mb-4">Hackathon Nasional untuk Malaysia Madani</h2>
        <p className="max-w-2xl text-lg">
          MYHackathon is Malaysia's national scale hackathon involving not only technopreneurs, innovators and subject
          matter experts but also concerned Malaysians from all walks of life, to come together to co-create digital
          solutions that will help improve the delivery of key government's services.
        </p>
      </div>
    </section>
  )
}
